---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit
          href: https://reddit.com/

- Entertainment:
    - Plex:
        - abbr: Pl
          icon: plex
          href: https://app.plex.tv/desktop/#!
    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/

- Productivity:
    - Google Calendar:
        - abbr: GCAL
          icon: google-calendar
          href: https://calendar.google.com/calendar/u/0/r
    - Gmail:
        - abbr: GM
          icon: gmail
          href: https://mail.google.com/mail/u/0/#inbox
- Health: 
    - Therapy:
        - abbr: TH
          icon: zoom
          href: https://us02web.zoom.us/j/7591338701?pwd=NFlhVTI1OTczbXZWa3JiY2FHRWFuZz09
        