---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/
