---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Dockerized Apps:
    - romm:
        icon: romm
        href: http://10.0.10.4:80
        description: Video Game Emulation
        widget:
            type: romm
            url: http://10.0.10.4:80
            fields: ["platforms", "totalRoms", "saves", "states"] # optional - default fields shown
        
    - mealie:
        icon: mealie
        href: http://10.0.10.4:9925/login
        description: Recipe Repository
        widget:
            type: mealie
            url: http://10.0.10.4:9925
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6IjQyYmNiMjdkLTgxMzgtNDc5Yy05MTdmLTBiMTVlZjZlZTUyZCIsIm5hbWUiOiJIb21lcGFnZSIsImludGVncmF0aW9uX2lkIjoiZ2VuZXJpYyIsImV4cCI6MTkyNTI3MTY4NH0.-QeD9qu3aI2HRaKP0HisZLZot5o3sieDTAWc-AQ3VME
            version: 2 # only required if version > 1, defaults to 1

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- Monitoring:
    - beszel:
        icon: beszel
        href: http://10.0.10.5:8090
        description: monitoring
        widget:
            type: beszel
            url: http://10.0.10.5:8090
            username: reckless.sr@gmail.com
            password: gD7gWzWre2gf
            systemId: systemId # optional
            version: 2 # optional, default is 1
