---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Dockerized Apps:
    - romm:
        icon: romm
        href: http://10.0.10.4:80
        description: Video Game Emulation
        widgets:
           - type: romm
             url: http://10.0.10.4:80
             fields: ["platforms", "totalRoms", "saves", "states"] # optional - default fields shown
           - type: beszel
             url: http://10.0.10.5:8090
             username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
             password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
             systemId: d1ddc471b3f1
             version: 2 # optional, default is 1
             fields: ["name", "status", "updated", "cpu", "memory", "disk", "network"]
    - mealie:
        icon: mealie
        href: http://10.0.10.4:9925
        description: Recipe Repository
        widget:
            type: mealie
            url: http://10.0.10.4:9925
            key: {{HOMEPAGE_VAR_MEALIE_API_KEY}}
            version: 2 # only required if version > 1, defaults to 1

#- My Second Group:
#    - My Second Service:
#        href: http://localhost/
#        description: Homepage is the best

- Monitoring:
    - beszel:
        icon: beszel
        href: http://10.0.10.5:8090
        description: monitoring
        widget:
            type: beszel
            url: http://10.0.10.5:8090
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
            version: 2 # optional, default is 1
    - synology diskstation:
        icon: synology
        href: http://10.0.10.3:5000
        description: Network Attached Storage        
        widget:
            type: diskstation
            url: http://10.0.10.3:5000
            username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
            password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}
            volume: volume_1 # optional

- Daiimus's Services:
    - radarr:
        icon: radarr
        href: http://100.100.192.19:7878/
        description: arr movies
        widget:
            type: radarr
            url: http://100.100.192.19:7878/
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
            enableQueue: false # optional, defaults to false
    - sonarr:
        icon: sonarr
        href: http://100.100.192.19:8989/
        description: arr shows
        widget:
            type: sonarr
            url: http://100.100.192.19:8989/
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
            enableQueue: false # optional, defaults to false
       
