---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Dockerized Apps:
    - romm:
        icon: romm
        href: http://10.0.10.4:80
        description: Video Game Emulation
        widget:
            type: romm
            url: http://10.0.10.4:80
            fields: ["platforms", "totalRoms", "saves", "states"] # optional - default fields shown
        
    - mealie:
        icon: mealie
        href: http://10.0.10.4:9925/login
        description: Recipe Repository
        widget:
            type: mealie
            url: http://10.0.10.4:9925
            key: {{HOMEPAGE_VAR_MEALIE_API_KEY}}
            version: 2 # only required if version > 1, defaults to 1

#- My Second Group:
#    - My Second Service:
#        href: http://localhost/
#        description: Homepage is the best

- Monitoring:
    - beszel:
        icon: beszel
        href: http://10.0.10.5:8090
        description: monitoring
        widget:
            type: beszel
            url: http://10.0.10.5:8090
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
            version: 2 # optional, default is 1
