---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  mealie: ${MEALIE_API_KEY}
  beszel:
    username: ${BESZEL_USERNAME}
    password: ${BESZEL_PASSWORD}
